import aiohttp
import asyncio
from argparse import Namespace
from asyncio import AbstractEventLoop
from datetime import datetime
from logging import Logger
from mqtt_helper import MqttHelper
from paho.mqtt.client import Client, MQTTMessage, ConnectFlags, DisconnectFlags
from paho.mqtt.enums import MQTTProtocolVersion
from paho.mqtt.reasoncodes import ReasonCode
from paho.mqtt.properties import Properties
from types import FrameType
from typing import Protocol, Any, Callable, Coroutine, Mapping, TypeVar

_T = TypeVar("_T")


class GoveeServiceProtocol(Protocol):
    api_calls: int
    api_key: str
    args: Namespace | None
    boosted: list[str]
    client_id: str
    command_locks: dict[str, asyncio.Lock]
    _pending_commands: dict[str, dict[str, Any]]
    config: dict[str, Any]
    device_interval: int
    device_list_interval: int
    device_boost_interval: int
    devices: dict[str, Any]
    discovery_complete: bool
    events: list
    last_call_date: datetime
    logger: Logger
    loop: AbstractEventLoop
    mqtt_config: dict[str, Any]
    mqtt_connect_time: datetime
    mqtt_helper: MqttHelper
    mqtt_protocol: MQTTProtocolVersion
    mqttc: Client
    qos: int
    rate_limited: bool
    running: bool
    service_name: str
    service: str
    session: aiohttp.ClientSession
    states: dict[str, Any]
    timezone: str

    async def build_component(self, device: dict[str, Any]) -> str: ...
    async def build_device_states(self, device_id: str, data: dict[str, Any] = {}) -> None: ...
    async def build_air_purifier(self, air_purifier: dict[str, Any]) -> str: ...
    async def build_humidifier(self, humidifier: dict[str, Any]) -> str: ...
    async def build_light(self, light: dict[str, Any]) -> str: ...
    async def build_sensor(self, sensor: dict[str, Any]) -> str: ...
    async def device_boosted_loop(self) -> None: ...
    async def device_list_loop(self) -> None: ...
    async def device_loop(self) -> None: ...
    async def get_device(self, device_id: str) -> dict[str, Any]: ...
    async def get_device_list(self) -> list[dict[str, Any]]: ...
    async def get_device_scenes(self, device_id: str) -> list[dict[str, Any]]: ...
    async def handle_device_topic(self, components: list[str], payload: Any) -> None: ...
    async def handle_homeassistant_message(self, payload: str) -> None: ...
    async def handle_service_message(self, handler: str, message: Any) -> None: ...
    async def heartbeat(self) -> None: ...
    async def main_loop(self) -> None: ...
    async def mqttc_create(self) -> None: ...
    async def mqtt_on_connect(
        self, client: Client, userdata: dict[str, Any], flags: ConnectFlags, reason_code: ReasonCode, properties: Properties | None
    ) -> None: ...
    async def mqtt_on_disconnect(
        self, client: Client, userdata: Any, flags: DisconnectFlags, reason_code: ReasonCode, properties: Properties | None
    ) -> None: ...
    async def mqtt_on_log(self, client: Client, userdata: Any, paho_log_level: int, msg: str) -> None: ...
    async def mqtt_on_message(self, client: Client, userdata: Any, msg: MQTTMessage) -> None: ...
    async def mqtt_on_subscribe(self, client: Client, userdata: Any, mid: int, reason_code_list: list[ReasonCode], properties: Properties) -> None: ...
    async def post_command(self, device_id: str, sku: str, capability: dict[str, Any], instance: str, value: str) -> dict[str, Any]: ...
    async def prepare_device(self, device: dict[str, Any], raw_id: str, device_id: str, type: str) -> None: ...
    async def publish_device_availability(self, device_id: str, online: bool = True) -> None: ...
    async def publish_device_discovery(self, device_id: str) -> None: ...
    async def publish_device_state(self, device_id: str) -> None: ...
    async def publish_service_availability(self, status: str = "online") -> None: ...
    async def publish_service_discovery(self) -> None: ...
    async def publish_service_state(self) -> None: ...
    async def rediscover_all(self) -> None: ...
    async def refresh_all_devices(self) -> None: ...
    async def refresh_boosted_devices(self) -> None: ...
    async def refresh_device_list(self) -> None: ...
    async def send_command(self, device_id: str, attribute: str, command: Any) -> None: ...

    def _assert_no_tuples(self, data: Any, path: str = "root") -> None: ...
    def _get_device_lock(self, device_id: str) -> asyncio.Lock: ...
    def _get_pending_commands(self, device_id: str) -> dict[str, Any]: ...
    def _normalize_color_key(self, key: str) -> str: ...
    async def _send_single_command(self, device_id: str, attribute: str, command: Any) -> None: ...
    def _handle_signal(self, signum: int, frame: FrameType | None = None) -> None: ...
    def _parse_device_topic(self, components: list[str]) -> list[str | None] | None: ...
    def _wrap_async(
        self,
        coro_func: Callable[..., Coroutine[Any, Any, _T]],
    ) -> Callable[..., None]: ...

    def build_govee_capabilities(self, device_id: str, attribute: str, payload: Any) -> dict[str, dict]: ...
    def build_light_components(self, device_id: str, light: dict[str, Any], scenes: list[dict[str, Any]] | None = None) -> dict[str, dict[str, Any]]: ...
    def classify_device(self, device: dict[str, Any]) -> str: ...
    def find_key_by_value(self, d: Mapping[Any, Any], target: Any) -> Any: ...
    def get_device_name(self, device_id: str) -> str: ...
    def get_device_sku(self, device_id: str) -> str: ...
    def get_headers(self) -> dict[str, str]: ...
    def get_raw_id(self, device_id: str) -> str: ...
    def heartbeat_ready(self) -> None: ...
    def increase_api_calls(self) -> None: ...
    def is_discovered(self, device_id: str) -> bool: ...
    def load_config(self, config_arg: Any | None = None) -> dict[str, Any]: ...
    def mark_ready(self) -> None: ...
    def number_to_rgb_bluepop(self, number: int, max_value: int, brightness: int = 255) -> dict[str, int]: ...
    def number_to_rgb_hsv(self, number: int, max_value: int, value: float = 1.0, saturation: float = 1.0) -> dict[str, int]: ...
    def number_to_rgb_linear(self, number: int, max_value: int) -> dict[str, int]: ...
    def read_file(self, file_name: str) -> str: ...
    def restore_state_values(self, api_calls: int, last_call_date: str) -> None: ...
    def restore_state(self) -> None: ...
    def rgb_to_number(self, rgb: list[int] | dict[str, int]) -> int: ...
    def safe_split_device(self, topic: str, segment: str) -> list[str]: ...
    def save_state(self) -> None: ...
    def set_discovered(self, device_id: str) -> None: ...
    def set_if_rate_limited(self, status: int) -> None: ...
    def _build_music_capability_value(self, device_id: str, overrides: Mapping[str, Any]) -> dict[str, int] | None: ...
    def _normalize_music_auto_color_state(self, value: Any, mapping: Mapping[str, int]) -> bool | None: ...
    def _normalize_music_rgb(self, value: Any, rgb_max: int | None = None) -> int | None: ...
    def _normalize_mode_numeric_value(self, value: Any) -> int | None: ...
    def _segment_option_label(self, segment_id: int) -> str: ...
    def _scene_component_key(self, instance: str) -> str: ...
    def _parse_segment_selection(self, selection: Any, segment_range: Mapping[str, int] | None = None) -> int | None: ...
    def _coerce_int_in_range(self, value: Any, minimum: int, maximum: int) -> int | None: ...
    def upsert_device(self, device_id: str, **kwargs: dict[str, Any] | str | int | bool | None) -> bool: ...
    def upsert_state(self, device_id: str, **kwargs: dict[str, Any] | str | int | bool | None) -> bool: ...
