from argparse import Namespace
from asyncio import AbstractEventLoop
from datetime import datetime, date
from logging import Logger
from mqtt_helper import MqttHelper
from paho.mqtt.client import Client, MQTTMessage, ConnectFlags, DisconnectFlags
from paho.mqtt.reasoncodes import ReasonCode
from paho.mqtt.properties import Properties
from types import FrameType
from typing import Protocol, Any

# grep -ERh --exclude interface.py 'def\s+[^_]' src/ | sed -E "s/^[[:space:]]+//g" | awk '{ print "   ", $0, "..." }' | sort


class GoveeServiceProtocol(Protocol):
    api_calls: int
    api_key: str
    args: Namespace | None
    boosted: list[str]
    client_id: str
    config: dict[str, Any]
    device_interval: int
    device_list_interval: int
    device_boost_interval: int
    devices: dict[str, Any]
    discovery_complete: bool
    events: list
    last_call_date: date
    logger: Logger
    loop: AbstractEventLoop
    mqtt_config: dict[str, Any]
    mqtt_connect_time: datetime
    mqtt_helper: MqttHelper
    mqttc: Client
    qos: int
    rate_limited: bool
    running: bool
    service_name: str
    service: str
    session: Any
    states: dict[str, Any]
    timezone: str

    async def device_boosted_loop(self) -> None: ...
    async def device_list_loop(self) -> None: ...
    async def device_loop(self) -> None: ...
    async def heartbeat(self) -> None: ...
    async def main_loop(self) -> None: ...
    async def refresh_all_devices(self) -> None: ...
    async def refresh_boosted_devices(self) -> None: ...
    async def refresh_device_list(self) -> None: ...

    def _assert_no_tuples(self, data: Any, path: str = "root") -> None: ...
    def _decode_payload(self, raw: bytes) -> Any: ...
    def _extract_scalar(self, val: Any) -> Any: ...
    def _handle_device_topic(self, components: list[str], payload: dict[str, Any]) -> None: ...
    def _handle_homeassistant_message(self, payload: str) -> None: ...
    def _handle_signal(self, signum: int, frame: FrameType | None = None) -> None: ...
    def _parse_device_topic(self, components: list[str]) -> list[str | None] | None: ...

    def build_component(self, device: dict[str, Any]) -> str: ...
    def build_govee_capabilities(self, device_id: str, attributes: dict[str, Any]) -> dict[str, dict]: ...
    def build_light(self, device: dict[str, Any]) -> str: ...
    def build_sensor(self, device: dict[str, Any]) -> str: ...
    def classify_device(self, device: dict[str, Any]) -> str: ...
    def find_key_by_value(self, d: dict[str, Any], target: str) -> Any: ...
    def get_api_calls(self) -> int: ...
    def get_component_type(self, device_id: str) -> dict[str, Any]: ...
    def get_component(self, device_id: str) -> dict[str, Any]: ...
    def get_device_availability_topic(self, device_id: str) -> str: ...
    def get_device_image_topic(self, device_id: str) -> str: ...
    def get_device_list(self) -> list[dict[str, Any]]: ...
    def get_device_name(self, device_id: str) -> str: ...
    def get_device_sku(self, device_id: str) -> str: ...
    def get_device_state_topic(self, device_id: str, mode_name: str = "") -> str: ...
    def get_device(self, device_id: str, sku: str) -> dict[str, Any]: ...
    def get_headers(self) -> dict[str, str]: ...
    def get_mode(self, device_id: str, mode_name: str) -> dict[str, Any]: ...
    def get_modes(self, device_id: str) -> dict[str, Any]: ...
    def get_raw_id(self, device_id: str) -> str: ...
    def handle_service_message(self, handler: str, message: str) -> None: ...
    def heartbeat_ready(self) -> None: ...
    def increase_api_calls(self) -> None: ...
    def is_discovered(self, device_id: str) -> bool: ...
    def is_rate_limited(self) -> bool: ...
    def load_config(self, config_arg: Any | None = None) -> dict[str, Any]: ...
    def mark_ready(self) -> None: ...
    def mqtt_on_connect(
        self, client: Client, userdata: dict[str, Any], flags: ConnectFlags, reason_code: ReasonCode, properties: Properties | None
    ) -> None: ...
    def mqtt_on_disconnect(self, client: Client, userdata: Any, flags: DisconnectFlags, reason_code: ReasonCode, properties: Properties | None) -> None: ...
    def mqtt_on_log(self, client: Client, userdata: Any, paho_log_level: int, msg: str) -> None: ...
    def mqtt_on_message(self, client: Client, userdata: Any, msg: MQTTMessage) -> None: ...
    def mqtt_on_subscribe(self, client: Client, userdata: Any, mid: int, reason_code_list: list[ReasonCode], properties: Properties) -> None: ...
    def mqttc_create(self) -> None: ...
    def number_to_rgb_bluepop(self, number: int, max_value: int, brightness: int = 255) -> dict[str, int]: ...
    def number_to_rgb_hsv(self, number: int, max_value: int, value: float = 1.0, saturation: float = 1.0) -> dict[str, int]: ...
    def number_to_rgb_linear(self, number: int, max_value: int) -> dict[str, int]: ...
    def post_command(self, device_id: str, sku: str, capability: dict[str, Any], instance: str, value: str) -> dict[str, Any]: ...
    def publish_device_availability(self, device_id: str, online: bool = True) -> None: ...
    def publish_device_discovery(self, device_id: str) -> None: ...
    def publish_device_state(self, device_id: str) -> None: ...
    def publish_service_availability(self, status: str = "online") -> None: ...
    def publish_service_discovery(self) -> None: ...
    def publish_service_state(self) -> None: ...
    def read_file(self, file_name: str) -> str: ...
    def rediscover_all(self) -> None: ...
    def refresh_device_states(self, device_id: str, data: dict[str, Any] = {}) -> None: ...
    def reset_api_call_count(self) -> None: ...
    def restore_state_values(self, api_calls: int, last_call_date: str) -> None: ...
    def restore_state(self) -> None: ...
    def rgb_to_number(self, rgb: list[int] | dict[str, int]) -> int: ...
    def safe_split_device(self, topic: str, segment: str) -> list[str]: ...
    def save_state(self) -> None: ...
    def send_command(self, device_id: str, command: dict[str, Any]) -> None: ...
    def set_discovered(self, device_id: str) -> None: ...
    def upsert_device(self, device_id: str, **kwargs: dict[str, Any] | str | int | bool | None) -> None: ...
    def upsert_state(self, device_id: str, **kwargs: dict[str, Any] | str | int | bool | None) -> None: ...
